name: edit_distance
description: Implementation of string distance algorithms.
version: 0.4.0
author: Kwang Yul Seo <email@example.com>
homepage: https://github.com/kioshi/edit_distance

environment:
  sdk: '>=2.0.0 < 3.0.0'

dev_dependencies:
  test: ^1.0.0

